apiVersion: v1
kind: Secret
metadata:
  namespace: kube-system
  name: csi-s3-secret
stringData:
  accessKeyID: "minio"
  secretAccessKey: "minio123"
  # For AWS set it to "https://s3.<region>.amazonaws.com"
  endpoint: "http://minio-kubeflow.apps.okd.ictnjpaas.com"
  # If not on S3, set it to ""
  region: ""
