apiVersion: v1
kind: Secret
metadata:
  namespace: kube-system
  name: csi-s3-Parastor-secret
stringData:
  accessKeyID: "mqvJyofMcXSec9yRjjO0d7uzOrhrRmHl"
  secretAccessKey: "ofro8hattenp6gm51rtdtrxf5ovgareh"
  # For AWS set it to "https://s3.<region>.amazonaws.com"
  endpoint: "http://192.168.208.10:20480"
  # If not on S3, set it to ""
  region: "us-east-1"
